name: deploy-workflow
on: [push]
jobs:
    deploy-job:
        runs-on: ubuntu-latest
        env:
          NODE_ENV: production
        steps:
            - name: Checks out repo
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '16.13.2'
                  # cache: 'npm' # https://github.com/actions/setup-node#caching-packages-dependencies
            - run: npm install --include=dev
            - run: npm run build
