name: deploy-workflow
on: create
jobs:
    deploy-job:
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        runs-on: ubuntu-latest
        env:
          NODE_ENV: production
        steps:
            - name: Checks out repo
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '16.13.2'
                  cache: 'npm' # https://github.com/actions/setup-node#caching-packages-dependencies
            - run: npm install --include=dev
            - run: npm run build
            - name: Set release version
              run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
            - id: 'auth'
              uses: 'google-github-actions/auth@v0'
              with:
                credentials_json: '${{ secrets.GCLOUD_SA_KEY }}'
            - id: 'upload-file'
              name: 'Publish SDK to Gcloud'
              uses: 'google-github-actions/upload-cloud-storage@v0'
              with:
                path: './dist/spresso.tracking.sdk.web.js'
                destination: 'spresso-sdk/tracking-web/${{ env.RELEASE_VERSION }}/spresso.tracking.sdk.web.js'
