name: prod-deploy-workflow
on:
    push:
      tags:
          - v**
jobs:
    deploy-job:
        runs-on: ubuntu-latest
        env:
            NODE_ENV: production
        steps:
            - name: Checks out repo
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '16.13.2'
                  cache: 'npm' # https://github.com/actions/setup-node#caching-packages-dependencies
            - run: npm install --include=dev
            - run: npm run build
            - name: Set release version
              run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
            - id: 'auth'
              uses: 'google-github-actions/auth@v0'
              with:
                  credentials_json: '${{ secrets.SPRESSO_GCLOUD_SA_KEY_PROD }}'
            - id: 'upload-file'
              name: 'Publish SDK to Gcloud'
              uses: 'google-github-actions/upload-cloud-storage@v0'
              with:
                  path: './dist/spresso.sdk.tracking.web.js'
                  destination: 'spresso-saas-prod-spresso-sdk-tracking-web/${{ env.RELEASE_VERSION }}'
            - id: 'update-docs'
              name: 'Update Docs'
              run: npm run docs:clear-and-build
            - id: 'publish-docs'
              name: 'Publish Docs'
              run: |
                git config user.name "github-actions[bot]"
                git config user.email "github-actions[bot]@users.noreply.github.com"
                git add docs -f
                git status
                git commit -m 'Automated docs publish'
                git push origin main
